---
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-dbench-pod
spec:
  nodeName: k8s-node2
  containers:
  - name: dbench
    image: zayashv/dbench:latest
    volumeMounts:
    - name: mypvc
      mountPath: /tmp
  restartPolicy: Never
  volumes:
  - name: mypvc
    hostPath: 
      path: /csi-data

