apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-hostpath-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: openebs-hostpath-dbench-pod
spec:
  containers:
  - name: dbench
    image: zayashv/dbench:latest
    volumeMounts:
    - name: mypvc
      mountPath: /tmp
  restartPolicy: Never
  volumes:
  - name: mypvc
    persistentVolumeClaim:
      claimName:  openebs-hostpath-pvc
