apiVersion: batch/v1
kind: Job
metadata:
  name: rook-nfs-dbench-job
spec:
  template:
    metadata:
      labels:
        app: dbench
    spec:
      nodeName: k8s-node2
      containers:
      - name: dbench
        image: zayashv/dbench:latest
        volumeMounts:
        - name: mypvc
          mountPath: /tmp
      restartPolicy: Never
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: rook-nfs-pvc
